appname: NeuralQA

ui:
  queryview:
    intro:
      title: "NeuralQA: Question Answering on Large Datasets"
      subtitle: "NeuralQA is an interactive tool for question answering (passage retrieval + document reading). You can manually provide a passage or select a search index from (e.g. case.law ) dataset under the QA configuration settings below. To begin, type in a question query below."
    views:
      intro: True
      advanced: True
      samples: False
      passages: True
      explanations: True
      allanswers: True
    options:
      model:
        title: QA models
        selected: distilbertsquad2
        options:
          - name: DistilBERT SQUAD2
            value: distilbertsquad2
          - name: BERT SQUAD2
            value: bertsquad2
      index:
        title: Search Index
        selected: manual
        options:
          - name: Manual
            value: manual
          - name: Case Law
            value: cases
          - name: Supremee Court
            value: cases
      stride:
        title: Token Stride
        selected: 0
        options:
          - name: 0
            value: 0
          - name: 50
            value: 50
          - name: 100
            value: 100
          - name: 200
            value: 200
      maxpassages:
        title: Passages
        selected: 5
        options:
          - name: 5
            value: 5
          - name: 10
            value: 10
          - name: 15
            value: 15
      highlightspan:
        title: IR Highlight Span
        selected: 250
        options:
          - name: 150
            value: 150
          - name: 250
            value: 250
          - name: 350
            value: 350
          - name: 450
            value: 450
          - name: 650
            value: 650

  header:
    appname: NeuralQA
    appdescription: Question Answering on Large Datasets

# server:
#   host: localhost
#   port: 3008
retriever:
  readtopn: 0
  relsnip: true
  index:
    - caselaw:
      name: Case Law
      index: cases
      host: localhost
      port: 9200
      type: elasticsearch
      enabled: False
    - supremecourt:
      name: Supreme Court Docs
      index: supremecourt
      host: localhost
      port: 9200
      type: elasticsearch
      enabled: False

reader:
  models:
    - distilbertsquad2:
      name: distilbertsquad2
      path: twmkn9/distilbert-base-uncased-squad2
      type: distilbert
      enabled: True
    - bertsquad2:
      name: bertsquad2
      path: deepset/bert-base-cased-squad2
      type: bert
      enabled: False
    # - bertlargesquad2:
    #   name: distillbertsquad1
    #   path: deepset/bert-large-uncased-whole-word-masking-squad2
    #   type: bert
    #   enabled: False

expander:
  - maskedlm:
    name: maskedlm
    path: pathtomaskedlm
    enabled: True
  - word2vec:
    name: word2vec
    path: pathtoword2vecmodel
    enabled: True
