appName: neuralqa
logLevel: WARN

models:
  supported:
    - distillbertsquad2:
      name: distillbertsquad2
      link: distillbertsquad2
    - distillbertsquad1:
      name: distillbertsquad1
      link: distillbertsquad1
