appname: neuralqa
loglevel: WARN

ui:
  backend:
    host: localhost
    port: 3008
  frontend:
    view:
      advanced: False
      samples: False
      passages: True
      explanations: True
    data:
      title: "NeuralQA: Question Answering on Large Datasets"
      subtitle: "NeuralQA is an interactive tool for question answering (passage retrieval + document reading). You can manually provide a passage or select a search index from (e.g. case.law ) dataset under the QA configuration settings below. To begin, type in a question query below."

searchindex:
  supported:
    - caselaw:
      name: Case Law
      index: cases
      host: localhost
      port: 9200
    - supremecourt:
      name: Supreme Court Docs
      index: supremecourt
      host: localhost
      port: 9200

models:
  supported:
    - distilbertsquad2:
      name: distilbertsquad2
      path: twmkn9/distilbert-base-uncased-squad2
      type: distilbert
    - bertsquad2:
      name: bertsquad2
      path: deepset/bert-base-cased-squad2
      type: bert
    - bertlargesquad2:
      name: distillbertsquad1
      path: deepset/bert-large-uncased-whole-word-masking-squad2
      type: bert
